name: translucent_navigation_bar
description: Implementation of Translucent Navigation Bar.
version: 1.0.0
homepage: https://github.com/AsimBhadra/translucent_navigation_bar

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  lints: ^1.0.1

flutter:
